<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%
 if(request.getSession().getAttribute("user")==null){
	 response.sendRedirect("login.jsp");
 }
%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Report Page</title>
<%@include file="/includes/header.jsp"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

</head>
<body>
	<%@include file="/includes/navbar.jsp"%>
	<div class="container mt-5">
		 <h2>Generate Report</h2>
		 <form action="generateReport" method="post">
			 <div class="form-group">
				 <label for="reportType">Report Type:</label>
				 <input type="text" class="form-control" id="reportType" name="reportType" required>
			 </div>
			 <div class="form-group">
				 <label for="generatedBy">Generated By (User ID):</label>
				 <input type="number" class="form-control" id="generatedBy" name="generatedBy" required>
			 </div>
			 <div class="form-group">
				 <label for="reportData">Report Data:</label>
				 <textarea class="form-control" id="reportData" name="reportData" rows="5" required></textarea>
			 </div>
			 <button type="submit" class="btn btn-primary">Generate Report</button>
		 </form>
	 </div>
	 
	 <div class="container mt-5">
		 <h2>Generated Reports</h2>
		 <table class="table table-bordered">
			 <thead>
				 <tr>
					 <th>ID</th>
					 <th>Report Type</th>
					 <th>Generated By</th>
					 <th>Generated At</th>
					 <th>Report Data</th>
			 	</tr>
			 </thead>
			 <tbody>
				 <c:forEach var="report" items="${reportList}">
					 <tr>
						 <td>${report.id}</td>
						 <td>${report.reportType}</td>
						 <td>${report.generatedBy}</td>
						 <td>${report.generatedAt}</td>
						 <td>${report.reportData}</td>
					 </tr>
				 </c:forEach>
			 </tbody>
	 	</table>
	 </div>
	<%@include file="/includes/footer.jsp"%>

</body>
</html>